name: GPA Calculator – Multi-Version Archive

on:
  # Trigger on push to main or master branches
  push:
    branches:
      - master
      - main

  # Trigger on pull requests to main or master
  pull_request:
    branches:
      - master
      - main

  # Allow running manually from GitHub Actions UI
  workflow_dispatch:

# Allow only one deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

# Define environment variables
env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.8
  FLET_CLI_VERSION: 0.27.5
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python environment
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Install Flet CLI
      - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${FLET_CLI_VERSION}

      # Step 4: Build Flet Web App
      - name: Flet Build Web
        run: |
          echo "Building web app for repo: ${GITHUB_REPOSITORY}"
          # Set the correct base URL to match your repo name (important!)
          flet build web --base-url GPA-Mangement-System-In-Python --route-url-strategy hash

      # Step 5: Upload web build artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 1: Setup Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 2: Deploy built app to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
